version: '3'

services:
  sora:
    container_name: sora
    command: tail -f /dev/null #npm run dev
    restart: always
    environment:
      - NODE_PATH=<path_to_project_directory>/node_modules:<path_to_project_directory>/
    build:
      context: <path_to_project_directory>/
      args:
        project_home: <path_to_project_directory>/
        production_flag:
    volumes:
      - <path_to_project_directory>/:<path_to_project_directory>/:rw
      - <path_to_project_directory>/node_modules # hack to exclude node_modules from mapping
    depends_on:
      - postgres
    ports:
      - "8000:8000"
      - "9229:9229"
    networks:
      - app-connect

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "15432:5432"
    volumes:
      - ~/sora/PostgreSQL:/var/lib/postgresql/data
    networks:
      - app-connect

networks:
  app-connect:
    driver: bridge
