version: '3'

services:
  sora:
    container_name: sora
    command: tail -f /dev/null #npm run dev
    restart: always
    environment:
      - PORT=8000
    build:
      context: .
      args:
        project_home: /install
        production_flag:
    volumes:
      - .:/install/:rw
      - ./node_modules # hack to exclude node_modules from mapping
    depends_on:
      - postgres
    ports:
      - "8000:8000"
      - "9229:9229"
    networks:
      - app-connect

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "15432:5432"
    volumes:
      - ~/sora/PostgreSQL:/var/lib/postgresql/data
    networks:
      - app-connect

networks:
  app-connect:
    driver: bridge
